using System.Text.Json;
using System.Text.Json.Serialization;
using fyserver.Models;

namespace fyserver.Serialization;

/// <summary>
/// System.Text.Json 源生成上下文（AOT 友好）。
/// 覆盖 minimal API 的 body 绑定类型与主要响应/存储类型；
/// 通过 TypeInfoResolverChain 注册到 HTTP JSON 选项与 GameConstants.JsonOptions。
/// </summary>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower, WriteIndented = false)]
[JsonSerializable(typeof(Session))]
[JsonSerializable(typeof(ProviderDetail))]
[JsonSerializable(typeof(LobbyPlayer))]
[JsonSerializable(typeof(CreateDeck))]
[JsonSerializable(typeof(ChangeDeck))]
[JsonSerializable(typeof(DeckAction))]
[JsonSerializable(typeof(MatchPut))]
[JsonSerializable(typeof(MatchActionEn))]
[JsonSerializable(typeof(MulliganCards))]
[JsonSerializable(typeof(SessionResponse))]
[JsonSerializable(typeof(MiniSitNGo))]
[JsonSerializable(typeof(StoreResponse))]
[JsonSerializable(typeof(StoreConfig))]
[JsonSerializable(typeof(StoreGroup))]
[JsonSerializable(typeof(StoreOffer))]
[JsonSerializable(typeof(StoreItem))]
[JsonSerializable(typeof(StoreItemData))]
[JsonSerializable(typeof(AlwaysFeaturedGroup))]
[JsonSerializable(typeof(ItemsResponse))]
[JsonSerializable(typeof(EquippedItem))]
[JsonSerializable(typeof(Item))]
[JsonSerializable(typeof(Entitlement))]
[JsonSerializable(typeof(FriendsReponse))]
[JsonSerializable(typeof(LibraryResponse))]
[JsonSerializable(typeof(LibraryItem))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(BannedResponse))]
[JsonSerializable(typeof(Error))]
[JsonSerializable(typeof(Config))]
[JsonSerializable(typeof(fyserver.Models.Endpoints))]
[JsonSerializable(typeof(CurrentUser))]
[JsonSerializable(typeof(Claim))]
[JsonSerializable(typeof(ClaimItem))]
[JsonSerializable(typeof(ClaimItemData))]
[JsonSerializable(typeof(PostMatchResponse))]
[JsonSerializable(typeof(MatchResponse))]
[JsonSerializable(typeof(DeckCardsResult))]
[JsonSerializable(typeof(CardLookup))]
[JsonSerializable(typeof(User))]
[JsonSerializable(typeof(Deck))]
[JsonSerializable(typeof(MatchInfo))]
[JsonSerializable(typeof(MatchAction))]
[JsonSerializable(typeof(MatchCard))]
[JsonSerializable(typeof(MatchLocation))]
[JsonSerializable(typeof(MulliganResult))]
[JsonSerializable(typeof(MatchStartingInfo))]
[JsonSerializable(typeof(MatchAndStartingData))]
[JsonSerializable(typeof(MatchData))]
[JsonSerializable(typeof(StartingData))]
[JsonSerializable(typeof(MatchReconnect))]
[JsonSerializable(typeof(WebSocketMessage))]
[JsonSerializable(typeof(WsNotification))]
[JsonSerializable(typeof(ClientInfo))]
[JsonSerializable(typeof(Card))]
[JsonSerializable(typeof(Library))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(List<object>))]
public partial class FyJsonContext : JsonSerializerContext;
